name: Publish to pub.dev

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2 # Installs Flutter SDK
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        env:
          PUB_CREDENTIALS: ${{ secrets.DART_SITE_CREDENTIALS }}
        run: flutter pub publish --force
